import type { MetadataRoute } from 'next';
import { SITE_URL } from '@/lib/site';

/**
 * robots.txt. Generated by Next from this file.
 *
 * - Crawlable: the index, the editorial feeds, and the show/venue detail pages
 *   (all CDN-cached now, so crawling them is cheap).
 * - Off-limits: the API (machines should use /api/v1 or the MCP server, not
 *   scrape HTML), the admin area, the tracked-redirect endpoint, and `/punt`
 *   (its `?s=` "spin again" links are an infinite URL space — a classic crawl
 *   trap). `/shows?` filter permutations are blocked for the same reason while
 *   leaving the bare `/shows` index and `/shows/<slug>` pages crawlable.
 *   `/shows-index` is the internal rewrite target for the bare `/shows`
 *   (its canonical points back) — no reason to index the same page twice.
 *
 * robots.txt is advisory — well-behaved crawlers honour it; `middleware.ts`
 * hard-blocks the ones that don't.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/admin', '/r', '/punt', '/shows?', '/shows-index'],
        crawlDelay: 10,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
